version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:4.4
    container_name: campus-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: campus_manager
    networks:
      - campus-network
     healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 }).ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: campus-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=campus_manager
      - CORS_ORIGINS=*
      - JWT_SECRET=your-secret-key-change-in-production-2024
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - campus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.16.180.19:8001/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campus-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - campus-network
    environment:
      - REACT_APP_BACKEND_URL=http://172.16.180.19:8001

networks:
  campus-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
